const menu = [
  {
    id: 1,
    title: "buttermilk pancakes",
    category: "breakfast",
    price: 15.99,
    img: "https://th.bing.com/th/id/OIP.gpTfz6sj9uVWFxUp-2gLKQHaE7?w=271&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: "diner double",
    category: "lunch",
    price: 13.99,
    img: "https://th.bing.com/th/id/OIP.OHn_NEULxvcnZ8NiKmfbagHaDO?w=330&h=152&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: "godzilla milkshake",
    category: "shakes",
    price: 6.99,
    img: "https://th.bing.com/th/id/OIP.-Wz6aODPfIh7QrJXFbsfWQHaF3?w=217&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: "country delight",
    category: "breakfast",
    price: 20.99,
    img: "https://th.bing.com/th/id/OIP.sJ2uHW2ov2t50HvN15sKLAHaFL?w=266&h=185&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: "egg attack",
    category: "lunch",
    price: 22.99,
    img: "https://th.bing.com/th/id/OIP.fjBy6tQi-LhLpXrxjxW90AHaLH?w=182&h=273&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: "oreo dream",
    category: "shakes",
    price: 18.99,
    img: "https://th.bing.com/th?id=OIP.1dT7sW1K-kEhUu58BHstYAHaLH&w=204&h=306&c=8&rs=1&qlt=90&o=6&dpr=1.3&pid=3.1&rm=2",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: "bacon overflow",
    category: "breakfast",
    price: 8.99,
    img: "https://th.bing.com/th/id/OIP.wUZ6JPHwFquufQVutEVHjQHaHa?w=182&h=182&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: "american classic",
    category: "lunch",
    price: 12.99,
    img: "https://th.bing.com/th/id/OIP.OeBhHpa4vxb9QP-uyPp_tAHaEc?w=302&h=181&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: "quarantine buddy",
    category: "shakes",
    price: 16.99,
    img: "https://th.bing.com/th/id/OIP.pbNPVzW8uCCtfeCJbVyAGwHaE8?w=272&h=181&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
]
export default menu
